#Deployment Yaml for Findoc-cms

apiVersion: apps/v1
kind: Deployment
metadata:
  name: findoc-finance
spec:
  selector:
    matchLabels:
      app: findoc-finance
  template:
    metadata:
      labels:
        app: findoc-finance
    spec:
      containers:
      - name: findoc-finance
        image: DOCKER_IMAGE
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 2276
        envFrom:
        - configMapRef:
            name: Findost-finanace-configmap
