name: Docker Image CI

on:
  push:
    branches: [ pre-production ]
  pull_request:
    branches: ["pre-production"]

env:
  IMAGE_NAME: cms-dep

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Amazon ECR Details
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}

      - name:
        id: login-pf-aws-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build and push
        env:
          ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO}}
          IMAGE_TAG: latest
        run: |
          cd depolyment/
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG


      - name: Update deployment.yaml
        run: | 
          sed -i "s|KarthyDevops/cms-dep.*|KarthyDevops/${{env.IMAGE_NAME}}:${{github.run_number}}|g" deployment/finance-deployment.yaml

          cat deployment/finance-deployment.yaml
      - name: commit changes
        run: |
          git config --local user.mail "karthy.shunmugam@gmail.com"
          git config --local user.name "KarthyDevops"
          git add .
          git commit -m "Update deployment.yaml with new Docker image [skip ci]"

        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
