name: Docker Image CI

on:
  push:
    branches: [ pre-production ]
  pull_request:
    branches: ["pre-production"]

env:
  IMAGE_NAME: cms-dep

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with: 
          context: ./deployment
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.run_number}}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Update deployment.yaml
        run: | 
          sed -i "s|KarthyDevops/cms-dep.*|KarthyDevops/${{env.IMAGE_NAME}}:${{github.run_number}}|g" deployment/finance-deployment.yaml

          cat deployment/finance-deployment.yaml
      - name: commit changes
        run: |
          git config --local user.mail "karthy.shunmugam@gmail.com"
          git config --local user.name "KarthyDevops"
          git add .
          git commit -m "Update deployment.yaml with new Docker image [skip ci]"

        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
